#Numpy nedir?
Başlangıçta Jim Hugunin tarafından çeşitli geliştiricilerin katkılarıyla oluşturuldu. 2005 yılında Travis Oliphant rakibi olan Numarray'in özelliklerini Numeric'e kapsamlı değişikliklerle dahil ederek NumPy'yi yarattı. NumPy, açık kaynaklı bir yazılımdır ve birçok katkıda bulunulmaktadır.

NumPy bilimsel ölçümler için temel bir Python paketi olmasının yanında. Diğer şeylerin yanı sıra aşağıdakileri de içerir:

<ol>
  <li>Güçlü bir N-boyutlu dizi nesnesi.</li>
  <li>Sofistike (yayıncılık) fonksiyonlar.</li>
  <li>C / C ++ ve Fortran kodunu bütünleştirme araçları.</li>
  <li>Kullanışlı doğrusal cebir, Fourier dönüşümü ve rasgele sayı yetenekleri.</li>
  <li>Keyfi veri türleri tanımlanabilir. Bu, NumPy'nin çok çeşitli veritabanlarıyla kesintisiz ve hızlı bir şekilde entegre olmasını sağlar.</li>
</ol>

##Nasıl yüklenir?

<ol>
  <li>En son sürüm NumPy ve SciPy paketlerini yüklemek için;</li>
  <p>git clone https://github.com/numpy/numpy.git numpy</p>
  <p>git clone https://github.com/scipy/scipy.git</p>
  <li>İnen setup.py dosyalarını kurmak için;</li>
  <p>python setup.py build</p>
  <p>python setup.py install</p>
  <li>Eğer PyCharm kullanıyorsanız, "import numpy" çıkan kırmızı lamba ile otomatik yükletebilirsiniz.</li>
</ol>

<p></p>

#Basit İşlemler

In [3]:
from numpy import *

a = array([1,2,3,4])
b = array((2,3,4,5))

In [8]:
a+b,a*b,a**b,a/b

(array([3, 5, 7, 9]),
 array([ 2,  6, 12, 20]),
 array([   1,    8,   81, 1024]),
 array([ 0.5       ,  0.66666667,  0.75      ,  0.8       ]))

In [12]:
sin(a) , cos(b)

(array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ]),
 array([-0.41614684, -0.9899925 , -0.65364362,  0.28366219]))

#Matplotlib

Değerlerimizi daha iyi görmemizi sağlayacak bir kütüphane daha.

In [19]:
import matplotlib.pyplot as plt

plt.plot(a,b)